repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: jetstack 
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana 
    url: https://grafana.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  # https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: ^1.3.1
    values:
      - installCRDs: true

  # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  # Uncomment if your cluster not have ingress-nginx by default
  # - name: ingress-nginx
  #   chart: ingress-nginx/ingress-nginx
  #   version: ^3.35.0

  # https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: ^4.5.0
    values:
      - ingress:
          enabled: true
          hosts:
            - {{ env "K8S_DASHBOARD_HOST" | default "dashboard.k8s.local" }} 
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
          tls:
            - hosts:
              - {{ env "K8S_DASHBOARD_HOST" | default "dashboard.k8s.local" }} 
              secretName: kubernetes-dashboard-tls
      - metricsScraper: 
          enabled: true
      - metrics-server:
          enabled: true 

  # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  - name: kube-prometheus-stack
    namespace: monitoring-logs-trace-stack
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: ^17.1.1
    values:
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/alertmanager/values.yaml
      - alertmanager:
          enabled: false
          config:
            receivers:
              - name: default-receiver
                # https://prometheus.io/docs/alerting/latest/configuration/#receiver
          ingress:
            enabled: false
            ingressClassName: nginx
            hosts:
              - {{ env "ALERT_MANAGER_HOST" | default "alertmanager.k8s.local" }}
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
            tls:
              - hosts:
                - {{ env "ALERT_MANAGER_HOST" | default "alertmanager.k8s.local" }}
                secretName: alertmanager-general-tls
      # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
      - grafana:
          enabled: true
          adminPassword: {{ env "GRAFANA_PASSSWORD" | default "prom-operator" }} 
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
            hosts:
                - {{ env "GRAFANA_HOST" | default "grafana.k8s.local" }}
            tls:
              - hosts:
                - {{ env "GRAFANA_HOST" | default "grafana.k8s.local" }}
                secretName: grafana-general-tls
  
  # https://artifacthub.io/packages/helm/grafana/loki-stack
  - name: loki
    namespace: monitoring-logs-trace-stack
    createNamespace: true
    chart: grafana/loki-stack
    version: ^2.4.1
    values:
      - promtail:
          enabled: true
      - fluent-bit: # can work faster, but plugin for loki not support pod labels
          enabled: false

  # https://artifacthub.io/packages/helm/grafana/tempo-distributed
  - name: tempo
    namespace: monitoring-logs-trace-stack
    createNamespace: true
    chart: grafana/tempo-distributed
    version: ^0.9.6

  # https://artifacthub.io/packages/helm/argo/argo-cd
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: ^3.11.1
    values:
      - installCRDs: false # for Helm 3 compitability
      - server:
          extraArgs:
            - --insecure # fix for https://github.com/argoproj/argo-cd/issues/2953
          ingress:
            enabled: true
            ingressClassName: nginx
            https: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ env "SERTIFICATE_ISSUER" | default "letsencrypt-staging" }}
            hosts:
              - {{ env "ARGO_HOST" | default "argo.k8s.local" }}
            tls:
              - hosts:
                - {{ env "ARGO_HOST" | default "argo.k8s.local" }}
                secretName: argo-general-tls
      - configs.secret.githubSecret: {{ env "ARGO_GITHUB_SECRET" | default "" }}
      - configs.secret.bitbucketSecret: {{ env "ARGO_BITBUCKET_SECRET" | default "" }}
      - configs.secret.gitlabSecret: {{ env "ARGO_GITLAB_SECRET" | default "" }}