repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: jetstack 
    url: https://charts.jetstack.io

releases:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: ^4.2.0
    values:
      - ingress:
          enabled: true
          hosts:
            - dashboard.k8s.local
          annotations:
            # will use stagging issuer for test configuration
            # change to letsencrypt-prod if sure all working correctly
            # lets encrypt can ban production config if you using it for experiments
            cert-manager.io/cluster-issuer: "letsencrypt-staging" 
          tls:
            - hosts:
              - dashboard.k8s.local
              secretName: kubernetes-dashboard-tls
      - metricsScraper: 
          enabled: true
      - metrics-server:
          enabled: true 

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: ^1.3.1
    values:
      - installCRDs: true