repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    createNamespace: true
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: ^2.8.3
    # values:
    #   - rbac: 
    #       clusterReadOnlyRole: true
      # - serviceAccount: 
      #     name: kubernetes-dashboard
      # - ingress:
      #     enabled: false
      # - metricsScraper: 
      #     enabled: false
      # - metrics-server:
      #     enabled: false # if running in minikube not need to create metrics server