apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # For additional fields see https://argoproj.github.io/argo-cd/operator-manual/application.yaml
  project: default
  source:
    repoURL: https://github.com/kubernetes/examples.git # also https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: # reference https://argoproj.github.io/argo-cd/user-guide/auto_sync/
    automated:
      prune: true
      selfHeal: true